minimum_reviewers: 2
merge: true
merge_method: merge
build_steps:
  - rebar3 clean --all
  - rebar3 compile
  - rebar3 as prod compile
  - rebar3 as check brt-deps --check
  - rebar3 as check xref
  - rebar3 as check dialyzer
  - rebar3 eunit
  - rebar3 edoc
org_mode: true
timeout: 1800
